### PR TITLE
Update to 6.7.0

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by hmaarrfk** [comment]
> ERROR: Qt Wayland Client requires QtGui to be build with support for wayland

I was trying to avoid adding new dependencies to QtGui.

I've personally been experimenting with Wayland, but in my application, I've had to force fallback to X11....

**Comment by hmaarrfk** [comment]
Why close?

**Comment by jschueller** [comment]
I though I'd just drop wayland and try to update pyside without it

**Comment by hmaarrfk** [comment]
hmm ok. i feel like that is a mistake long term, but I don't have the bandwidth to investigate fixing this right away.

**Comment by jschueller** [comment]
@conda-forge-admin, please restart ci​

**Comment by hmaarrfk** [comment]
Oh I see. You had tried to build this in the past. Just the bot and CDN was taking time.

**Pull request merged**
